client.py, configs/guillimin.config, configs/thuneri3g1.config, create_glidein_tarball.py, server.py, submit.py, util.py
Changed state send by server.py to state how many jobs of a certain kind need to be submitted. Adjusted submit.py and client.py accordingly. Resolves #10 and #16
=> First attempt at clustered submits and sorting jobs by priority

configs/T2_BE_IIHE.config
Here is the configuration used on our site.
=> Add T2_BE_IIHE config

submit.py
Remove mem attribute : only pmem is useful here
=> Only set pmem on PBS

client.py, client_util.py, configs/comet.config, server.py, submit.py
=> add client monitoring

configs/bartol.config, configs/comet.config, configs/comet.gpu.config, submit.py
Fixed parition typo. Also, parition was a key of self.config['Cluster'] and not of self.config. Make the partition parameter optional.
=> Fixes on slurm partition config and adds first version of config for Bartol

client.py, configs/comet.config, configs/comet.gpu.config, configs/guillimin.config, configs/jasper.config, configs/mainz_gpu.config, configs/npx.config, configs/osgconnect.config, configs/parallel.config, configs/thuneri3g1.config, configs/xsede_osg.config, configs/zeuthen.config, submit.py
PBS submit (and subclasses) now clear the env before running the glidein.
Still some configs to clean up.
=> Clear the env for pbs-like submitters

client.py, configs/zeuthen.cpu.config, glidein_template/user_job_wrapper.sh, submit.py
along with a max idle limit to avoid flooding a non-dedicated cluster
=> Add CPU config for Zeuthen

configs/bartol.config, submit.py
oops, I closed the previous request. I hadn't realized that the newer commits were added.
=> Changes again

glidein_start.sh
change glidein_start.sh to use extra collectors on glidein-simprod.icecube.wisc.edu
=> take advantage of multiple collectors on glidein-simprod

create_glidein_tarball.py
To get GSI working, we need to build condor like it's built at UW, with all the extras.  Granted, we turn off a bunch of them, but we still get globus and a few others.
=> get GSI working. bring along a lot of extras

pyglidein/submit.py
=> Adding presigned url variables to other pbs header sub modules

dev_build/client/root/etc/sv/pyglidein_client/htcondor_config, dev_build/client/root/etc/sv/pyglidein_client/run, dev_build/client_pbs_torque/root/etc/sv/pyglidein_client/pbs_torque_config, dev_build/docker-compose.yml, dev_build/docker-compose_pbs_torque.yml, dev_build/server/root/etc/sv/pyglidein_server/pyglidein_server.config, dev_build/server/root/etc/sv/pyglidein_server/run, dev_build/server/root/setup.sh, pyglidein/client.py, pyglidein/client_metrics.py, pyglidein/config.py, pyglidein/etc/client_defaults.cfg, pyglidein/metrics_sender_client.py, pyglidein/server.py, pyglidein/submit.py, setup.py, tests/integration/test_htcondor_glidein.py, tests/integration/test_pbs_torque_glidein.py
=> Adding support for client metrics

configs/T2_BE_IIHE.config
Will allow us to use upstream code without custom local changes.
=> Use new options. Requires #132 and #133.

pyglidein/client.py
=> Moving error logging to logging statement.

pyglidein/etc/client_defaults.cfg, pyglidein/submit.py
=> Fixed unsafe dict lookup.

pyglidein/glidein_start.sh
=> add a classad for if Parrot is enabled

pyglidein/client.py, pyglidein/client_metrics.py
Implemented client_metrics for LSF scheduler.
=> implemented client_metrics for LSF

.gitignore, configs/cedar.config, pyglidein/glidein_start_singularity.sh, pyglidein/submit.py, run.sh
Add singularity container functionality to glideins.
=> Singularity component

docs/configuration_index.md, docs/glidein_start_singularity.md, docs/index.md, pyglidein/glidein_start_singularity.sh
Added documentation for configuration files and singularity container usage.
=> Pyglidein docs update

configs/cedar.config, docs/configuration_index.md, pyglidein/glidein_start.sh
Implementation of a basic priority weighting system.
=> Add priority system to submissions

pyglidein/glidein_start_singularity.sh
This fixes an issue where multiple glideins on the same machine get the same glidein name
=> Assign unique hostnames to Singularity 3 containers

Dockerfile
(and updated my email address)
=> update the Dockerfile cuda image to cuda 10.2

pyglidein/client_metrics.py, pyglidein/client_util.py, pyglidein/daemon.py, pyglidein/server.py
This is a follow up on python2/3 string/bytes compatibility patches.
Both client and server are considered, and checks against the python version have been replaced by __future__.unicode_literals.
=> consistent string handling for python2/3 compatibility

pyglidein/server.py
As of version 5.0 of tornado IOloop.instance() has been deprecated and
doesn't return the main thread's IOloop.
Instead of passing the main threads IOLoop in a global variable across
threads, implementing condor_q as non-blocking coroutine seems cleaner
and more consistent.
=> IOloop.instance() doesn't work anymore in current tornado version.

.github/workflows/semantic-release.yml, pyglidein/__init__.py, setup.cfg, setup.py
closes https://github.com/WIPACrepo/pyglidein/issues/178
=> Semantic Release GH Action

configs/cedar.config
This is the current Cedar profile, and is likely the "final" iteration of it now that each of the profiles are working great.
=> Update Cedar config with CPU/GPU profiles

pyglidein/client_metrics.py
=> Ensure that command output is a string

configs/illume-v2.config
Illume-v2 profile. Only contains GPU profiles since we want to take advantage of the GPU density here.
=> Add illume-v2 profile
